apiVersion: apps/v1
kind: Deployment
metadata:
  name: performanceandscalability-deployment
  labels:
    app: performanceandscalability
spec:
  replicas: 3  # Número inicial de réplicas
  selector:
    matchLabels:
      app: performanceandscalability
  template:
    metadata:
      labels:
        app: performanceandscalability
    spec:
      containers:
        - name: performanceandscalability
          image: almeidapietra/performanceandscalability-service:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"  # Recursos mínimos reservados
              memory: "128Mi"
            limits:
              cpu: "500m"  # Recursos máximos que o contêiner pode usar
              memory: "256Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production  # Perfil do Spring ativo para ambiente de produção