apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: performanceandscalability-hpa
  labels:
    app: performanceandscalability
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: performanceandscalability-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Escalonar quando uso de CPU for acima de 50%